# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "app/src/db/schema.rs"
with_docs = true

[migrations_directory]
dir = "migrations"
